---
- name: Dell workstation setup
  hosts: dell
  gather_facts: true

  roles:
    - role: sourcejedi.rpmfusion_free
      become: true
      tags: [rpm]
    - role: fedora_dependencies
      become: true
      tags: [fedora_dependencies]
    - role: mise
      tags: [mise]
    - role: hostname
      become: true
      tags: [hostname]
    - role: jaredhocutt.gnome_extensions
      tags: [gnome_extensions]
    - role: ssh_config
      tags: [ssh_config]
    - role: git_config
      tags: [git_config]
    - role: generic_app
      vars:
        generic_app_name: "kDrive"
        generic_app_url: "https://download.storage.infomaniak.com/drive/desktopclient/kDrive-3.7.9.1-amd64.AppImage"
        generic_app_folder: "/opt/kDrive"
        generic_app_icon: "~/dotfiles/assets/kdrive.jpg"
        generic_app_exec: "env QTWEBENGINE_CHROMIUM_FLAGS=\"--no-sandbox\" QT_QPA_PLATFORM=xcb /opt/kDrive/kDrive"
        generic_app_autostart: "true"
        generic_app_categories: "Network;"
      tags: [kdrive]
    - role: jetbrains_toolbox
      tags: [jetbrains_toolbox]
    - role: gnome
      tags: [gnome]
    - role: commons
      tags: [commons]
