---
- name: Import repositories GPG keys
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item.gpg_url }}"
  loop: "{{ fedora_dependencies_repositories }}"

- name: Add repositories
  become: true
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.url }}"
    gpgkey: "{{ item.gpg_url }}"
    gpgcheck: "{{ item.gpg_check | bool }}"
  loop: "{{ fedora_dependencies_repositories }}"
