---
- name: Ensure direnv config exists
  ansible.builtin.file:
    mode: "0700"
    path: "~/.config/direnv"
    state: directory

- name: Template direnv config
  ansible.builtin.template:
    src: ./templates/direnv.toml.j2
    dest: ~/.config/direnv/direnv.toml
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
