---
- name: "Ensure folder does exists {{ item }}"
  ansible.builtin.file:
    mode: "0700"
    path: "~/{{ item | dirname }}"
    state: directory

- name: "Copy dotfile {{ item }}"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: ~/{{ item }}
    force: false
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0700"
