---
- hosts: localhost

  pre_tasks:
    - name: "Include locals vars"
      ansible.builtin.include_vars:
        file: "locals.yaml"
      tags: always

  roles:
    # ! - role: geerlingguy.docker
    # !   become: true
    - role: donhector.workstation.asdf
      tags: asdf
    - role: commons
      tags: commons
    - role: git_config
      tags: git
