---
- name: Ensure SSH config file exists
  ansible.builtin.copy:
    content: ""
    dest: "~/.ssh/config"
    force: false
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_uid }}"
    mode: "0600"

- name: Render SSH config Template
  ansible.builtin.set_fact:
    ssh_config_template: "{{ lookup('template', 'ssh_config.j2') }}"

- name: Add template in SSH config
  ansible.builtin.blockinfile:
    dest: "~/.ssh/config"
    block: |
      {{ ssh_config_template }}
    marker: "#{mark} ANSIBLE MANAGED BLOCK SSH"
